---
  - name: Config Web VM with Docker
    hosts: webservers
    tasks:
    - name: docker.io
      become: true
      apt:
        name: docker.io
        state: present

    - name: Install pip
      become: true
      apt:
        name: python-pip
        state: present

    - name: Install Docker python module
      pip:
        name: docker
        state: present
      become: true

    - name: download and launch a docker web container
      become: true
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80